name: 'Create Branch'
description: 'Creates a branch'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Action Token or PAT'
    required: true
  branch:
    description: 'The branch to create'
    required: false
    default: 'release-candidate'
  sha:
    description: 'The SHA1 value for the branch reference'
    required: false

outputs:
  created:
    description: 'Boolean value representing whether or not a new branch was created.'

runs:
  using: 'node12'
  main: 'dist/index.js'
